[project]
name = "dirac-agents"
version = "0.1.0"
description = "Agent and tool code for Dirac Agentic"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "smolagents",
  "huggingface_hub",
  "pillow"
  # Add other dependencies as needed
]
