apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: lhcb-dirac-dpa-mlops-llm-orchestrator
  labels:
    nvidia-drivers: "true"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    model:
      modelFormat:
        name: huggingface
      args:
        - --model_name=orchestrator
        - --model_id=Qwen/Qwen2.5-72B-Instruct-AWQ
        - --enable-auto-tool-choice
        - --tool-call-parser=hermes
      resources:
        limits:
          cpu: "8"
          memory: 64Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "4"
          memory: 48Gi
          nvidia.com/gpu: "1"
